### PR TITLE
Allow us to enable x-forwarded-for on all IPs

### LINKED ISSUE #195: Icecast-KH7 release doesn't appear to honor the X-Forwarded-For header
Hello! The radio management software I build uses icecast-kh built from the latest release here on Github, and also offers support for proxying listener traffic through nginx, with unique listener data preserved for licensing and royalty purposes.

Prior to the latest update, my software was pointing at the KH5 release. The listener data API endpoints in Icecast properly reported the forwarded IP from nginx. The recent update to KH7 appears to have reverted this functionality, instead showing only the direct IP (in this case, the nginx docker container's IP)

The relevant nginx proxy configuration is below:

```
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
```

I also included the "X-Real-IP" header as this is often used in other software.

If there is something I should be changing on my end to properly reflect the proxied listener IP, please let me know. Thank you!

### PR DESCRIPTION
**Pull request by CodeSteele**
Makes it so we have the option to switch a configuration on/off that fixes #195.

### CODE REVIEW

**Comment by crmb** [comment]
Yes, please

**Comment by CodeSteele** [comment]
Hey @karlheyes with the closing of #286 we're eyeballing having to pull upstream again for critical functionality, this functionality is the only thing I know of that is making us rely on our fork, so before I rebase this PR/pull your upstream changes, a few questions:

1) Is this something you're even interested in bringing in?
2) If so, other than obviously fixing the conflicts, is there anything you'd prefer I do with this to get it into a state where you'd be willing to pull it in?


Thanks!

**Comment by karlheyes** [comment]
I'm think that it would be better and more generic to use the wildcard match for this eg
```
<x-forwarded-for>*</x-forwarded-for>
or
<x-forwarded-for>192.168.*</x-forwarded-for>
```

karl

**Comment by SlvrEagle23** [comment]
@karlheyes I would definitely agree that wildcard support in the current x-forwarded-for config tags would be preferred; we had simply implemented this solution as a workaround for that not existing, as that would also perfectly solve the problem.

**Comment by karlheyes** [comment]
latest commit should now allow for the wildcard patterns.

karl

**Comment by SlvrEagle23** [comment]
@karlheyes Looking at the commit, it's a brilliantly simple solution that I think will actually work perfectly for situations like Docker, where we have a trusted range of IPs that we know of.

I believe this satisfies the existing requirements and @CodeSteele can probably close this one out for now.

Thank you very much for your help and for your ongoing contributions to the world of FOSS radio. :)

**Comment by CodeSteele** [comment]
Accomplished in e58e1de0f18422c71d54a74863acfc10e3c3a0e7

**Pull request closed without merging**
