### PR TITLE
Fixed empty buffer bug when an HTTP range request is made

### PR DESCRIPTION
**Pull request by onitake**
Addresses #134.
Fix is more of a hack, but should work fine for small files (like m3us).

### CODE REVIEW

**Comment by MaPePeR** [comment]
I'm in no way an expert on this, but seeing that you pass `client->intro_offset` directly into `pread` worries me a little bit. Are you sure that this is safe?

**Comment by onitake** [comment]
`offset` is the seek offset into the file. If it's out of bounds, `pread` will return an error.
So this should be totally safe, I think.

**Comment by onitake** [comment]
The only thing that's currently not safe, is that `client->refbuf` or `client->refbuf->next` could be `NULL`, or that `->next` is not the preallocated but empty content buffer.
But as far as I can see, this is always the case if `CLIENT_RANGE_END` is set. It's hard to tell, however. `fserve.c` is *very* convoluted...

**Comment by MaPePeR** [comment]
It's weird, that not handling the range header properly causes errors, because it is allowed to be ignored by the http standard. 

At least from what I found during my tiny research on that topic.

**Comment by onitake** [comment]
That is true, but the way this is implemented in icecast, the content buffer is simply never filled, only initialized to 0xff.

My patch fixes that, and it works in the limited testing context we did. But aside from the missing NULL checks, the patch should at least not be harmful in any way.

**Comment by onitake** [comment]
Looks like this bug is already fixed in HEAD. Retracting the pull request.

**Pull request closed without merging**
